### ISSUE TITLE
SPG_contributes.md wrong command

### ISSUE THREAD

**Issue by rayglo** [SE2-GROUP-P12/SPG#35]
In Documentation/SPG_contributes.md, are explained the instructions for starting the docker image with and without persistence at the closure. But the procedure looks the same, so even the result may be the same, despite the different intentions of the two. The passage is the following:

>#### Local db in docker container with persistence
>
>##### when to use it
>This is when you want to keep the changes in your local database, in fact the container will use a persistent volume as default option >in docker compose
>
>##### setup steps
>Launch the command `docker-compose up -d database`
>
>#### Local db in docker container without persistence
>
>##### when to use it
>This is when you don't want to keep the changes in your local database, the container will not use a persistent volume and all the >data will be cleaned when the container of the database is removed
>
>##### setup steps
>Launch the command `docker-compose up -d database`

So apparently the setup steps are identical and the command `docker-compose up -d database` is used for both purposes

**Comment by MattiaRiola** [comment]
thank you for the feedback, document now is consistent
