### ISSUE TITLE
It is not clear that I cannot buy decimal portions when shown in kg

### ISSUE THREAD

**Issue by include-jacopo** [SE2-GROUP-P12/SPG#59]

**Comment by MartinaSaugo** [comment]
If you write a decimal, an error will appear asking you to round it up. 

We chose to give the possibility to the farmer of choosing the unit of product he wants to sell. 
If a farmer chose as a unit a kilo, it means that he sells his/her products in bunchs of one kilo. 

We assumed that the ones that produce the items on the platform are the most fit to determine in which units to sell them.
If you go to any supermarket, you'll find bottles of milk of 1L each. If you need 1.5L you can buy either 1 or 2 bottles, but nobody will allow you to buy one bottle and a half.
