### ISSUE TITLE
Item number selection when adding a product to the cart

### ISSUE THREAD

**Issue by taurou** [SE2-GROUP-P12/SPG#60]
Selecting the number of units of an item with the on-screen keyboard or with the really small arrows at the right side of the form is not mobile-friendly.
Bigger + and - buttons would improve the experience on mobile devices.

**Comment by MartinaSaugo** [comment]
![s2](https://user-images.githubusercontent.com/79690902/144704431-ed0b209f-a16f-4415-bd14-dd4d6198e514.PNG)

The tiny arrows are a characteristic of the numeric input. 
As you can see from the screenshot, on mobile they're not present and the input is supposed to be introduced by keyboard, as on several other applications. 
We deemed the use of + and - buttons far less user friendly, especially handling big amounts.
